export enum DynamicProviderBindingStyle
{
   VALUE,
   CLASS,
   FACTORY_CLASS,
   FACTORY_METHOD_CALL,
   SUPPLIER_PROVIDED,
   SUPPLIER_PROVIDED_FACTORY,
   SUPPLIER_INJECTED_FUNCTION,
   CONSUMER_PROVIDED,
   CONSUMER_PROVIDED_FACTORY,
   CONSUMER_INJECTED_FUNCTION,
   // FACTORY_CALL_MUTUAL_DI,
}
