#!/bin/sh

readonly MODULE="packages/$1"
readonly AUTHOR="John Heinnickel"
readonly EMAIL="jheinnic@hotmail.com"

IFS='-' read -r -a parts <<< "$1"

for i in "${parts[@]}"; do
    INITIAL="$INITIAL${i:0:1}"
done

echo "generating module: $MODULE ($INITIAL)"
mkdir -p $MODULE

echo "creating /src & /typings & /test folders..."
mkdir -p $MODULE/src $MODULE/typings $MODULE/test
touch $MODULE/src/index.ts
touch $MODULE/typings/index.d.ts

cp packages/api/LICENSE $MODULE/

echo "writing test skeleton..."
cat << EOF > $MODULE/test/index.ts
// import * as assert from "assert";
// import * as $INITIAL from "../src/index";

describe("$1", () => {
    it("tests pending");
});
EOF

echo "writing package.json..."
cat << EOF > $MODULE/package.json
{
    "name": "@jchptf/$1",
    "version": "0.0.1",
    "description": "TODO",
    "main": "./dist/index.js",
    "typings": "./dist/index.d.ts",
    "repository": {
        "type": "git",
        "url": "https://github.com/jheinnic/portfolio-monorepo"
    },
    "author": "$AUTHOR <$EMAIL>",
    "license": "MIT",
    "scripts": {
        "build": "yarn run clean && tsc --declaration",
        "clean": "rm -rf dist/*.js dist/*.d.ts build .nyc_output build coverage doc; mkdir build",
        "cover": "yarn test && nyc report --reporter=lcov",
        "doc": "node_modules/.bin/typedoc --mode modules --out doc src typings",
        "pub": "yarn run build && yarn publish --access public",
        "test": "rm -rf build && mkdir build && tsc -p test && nyc mocha build/test/*.js"
    },
    "devDependencies": {
        "@types/chai": "^4.1.6",
        "@types/mocha": "^5.2.5",
        "@types/node": "^10.11.4",
        "@types/sinon": "^5.0.5",
        "chai": "^4.2.0",
        "mocha": "^5.2.0",
        "nyc": "^12.0.2",
        "sinon": "^7.0.0",
        "ts-sinon": "^1.0.12",
        "typedoc": "^0.13.0",
        "typescript": "^3.1.3"
   },
    "dependencies": {
        "simplytyped": "^1.5.2",
        "tslib": "^1.9.3"
    },
    "keywords": [
        "es6",
        "typescript"
    ],
    "publishConfig": {
        "access": "public"
    }
}
EOF

echo "writing module tsconfig.json..."
cat << EOF > $MODULE/tsconfig.json
{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
        "outDir": "./dist"
    },
    "include": [
        "./src/**/*.ts", "./typings/**/*.d.ts"
    ],
    "exclude": [
        "./dist",
        "./build",
        "./node_modules",
        "../*/typings",
        "../*/dist",
        "../*/build",
        "../*/node_modules"
    ]
}
EOF

echo "writing test tsconfig.json..."
cat << EOF > $MODULE/test/tsconfig.json
{
    "extends": "../../../tsconfig.json",
    "compilerOptions": {
        "outDir": "../build"
    },
    "include": [
        "./**/*.ts",
        "../src/**/*.ts",
        "../typings/**/*.d.ts"
    ],
    "exclude": [
        "../dist",
        "../build",
        "../node_modules",
        "../../*/typings",
        "../../*/dist",
        "../../*/build",
        "../../*/node_modules"
    ]
}
EOF

echo "writing .npmignore..."
cat << EOF > $MODULE/.npmignore
build
coverage
dev
doc
src*
test
.nyc_output
*.tgz
*.html
EOF

echo "writing README.md..."
cat << EOF > $MODULE/README.md
# @jchptf/$1

[![npm (scoped)](https://img.shields.io/npm/v/@jchptf/$1.svg)](https://www.npmjs.com/package/@jchptf/$1)
![npm downloads](https://img.shields.io/npm/dm/@jchptf/$1.svg)
[![Twitter Follow](https://img.shields.io/twitter/follow/jchptf_monorepo.svg?style=flat-square&label=twitter)](https://twitter.com/jchptf_monorepo)


This project is part of the
[@jchptf/portfolio-monorepo](https://github.com/jheinnic/portfolio-monorepo/) monorepo.

<!-- TOC depthFrom:2 depthTo:3 -->

<!-- /TOC -->

## About

TODO...

## Installation

\`\`\`bash
yarn add @jchptf/$1
\`\`\`

## Dependencies

- TODO...

## Usage examples

\`\`\`typescript
import * as $INITIAL from "@jchptf/$1";
\`\`\`

## Authors

- $AUTHOR

## License

&copy; 2018 $AUTHOR // MIT Software License
EOF
