export * from './application-binding-syntax.interface';
export * from './application-identifier.interface';
export * from './application-installer.interface';
export * from './concrete-factory-service.interface';
export * from './concrete-factory.interface';
export * from './container-registry.interface';
export * from './installer-adapter.interface';
export * from './installer-binding-syntax.interface';
export * from './installer-service.interface';
// export * from './installer-factory-creator.interface';
export * from './installer-identifier.interface';
export * from './installer-module-call-back.interface';
